### ISSUE TITLE
Implement Any<TSource>(IEnumerable<TSource>)

### ISSUE THREAD

**Issue by jreina** [ShittyLabs/DangerLinq#15]
Implement the [`Any<TSource>(IEnumerable<TSource>)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any?view=netcore-3.1#System_Linq_Enumerable_Any__1_System_Collections_Generic_IEnumerable___0__) function

**Comment by Jarrod2112** [comment]
I got this.
