### ISSUE TITLE
Implement Last<TSource>(IEnumerable<TSource>)

### ISSUE THREAD

**Issue by jreina** [ShittyLabs/DangerLinq#16]
Implement the Last<TSource>(IEnumerable<TSource>) function

https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.last?view=netcore-3.1#System_Linq_Enumerable_Last__1_System_Collections_Generic_IEnumerable___0__

**Comment by Jarrod2112** [comment]
I'll take it.
