### ISSUE TITLE
Create Where<T>

### ISSUE THREAD

**Issue by jreina** [ShittyLabs/DangerLinq#9]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.where?view=netcore-3.1#System_Linq_Enumerable_Where__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Boolean__

Reference existing code from [ShittyLinq.js.Where](https://github.com/ShittyLabs/ShittyLINQ.js/blob/develop/src/Where.js)

**Comment by Jarrod2112** [comment]
I'll take this one.

**Comment by Jarrod2112** [comment]
Gimme
